/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hc0FN5ObsHS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function HomePage() {
  return (
    <div className="flex min-h-[100dvh] flex-col bg-background text-foreground">
      <header className="container mx-auto px-4 py-8 md:py-12 lg:py-16">
        <div className="grid gap-6 md:grid-cols-2 md:gap-10 lg:gap-16">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">John Doe</h1>
            <h2 className="text-2xl font-medium text-muted-foreground sm:text-3xl md:text-4xl">
              Junior Software Engineer
            </h2>
            <p className="text-muted-foreground md:text-lg">
              I'm a passionate junior software engineer with a strong foundation in web development. I'm excited to
              contribute my skills and knowledge to innovative projects.
            </p>
            <div className="flex gap-4">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-6 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Download Resume
              </Link>
            </div>
          </div>
          <div className="flex items-center justify-center">
            <img src="/placeholder.svg" width="400" height="400" alt="Profile" className="rounded-full" />
          </div>
        </div>
      </header>
      <main className="container mx-auto px-4 py-8 md:py-12 lg:py-16">
        <div className="space-y-8">
          <div>
            <h2 className="mb-4 text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Experience</h2>
            <div className="relative flex flex-col gap-8">
              <div className="absolute left-1/2 top-0 h-full w-[2px] -translate-x-1/2 bg-muted" />
              <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-4">
                <div className="space-y-2 text-right">
                  <h3 className="text-lg font-medium">Junior Software Engineer</h3>
                  <p className="text-muted-foreground">Acme Inc.</p>
                  <p className="text-muted-foreground">2022 - Present</p>
                </div>
                <div className="relative flex items-center justify-center">
                  <div className="h-8 w-8 rounded-full bg-primary" />
                </div>
                <div className="space-y-2 text-left">
                  <p className="text-muted-foreground">
                    Developed and maintained web applications using React, Node.js, and SQL databases. Collaborated with
                    cross-functional teams to deliver high-quality software solutions.
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-4">
                <div className="space-y-2 text-right">
                  <h3 className="text-lg font-medium">Intern</h3>
                  <p className="text-muted-foreground">Widgets Inc.</p>
                  <p className="text-muted-foreground">2021 - 2022</p>
                </div>
                <div className="relative flex items-center justify-center">
                  <div className="h-8 w-8 rounded-full bg-primary" />
                </div>
                <div className="space-y-2 text-left">
                  <p className="text-muted-foreground">
                    Gained hands-on experience in web development, participating in the creation of responsive and
                    user-friendly web applications. Learned best practices in software engineering.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-muted py-6">
        <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 md:flex-row">
          <p className="text-muted-foreground">&copy; 2024 John Doe. All rights reserved.</p>
          <div className="flex gap-4">
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              LinkedIn
            </Link>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              GitHub
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
